# Generated by Django 3.2.3 on 2021-06-10 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
