# Generated by Django 3.2.3 on 2021-06-10 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_offering_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='name',
        ),
        migrations.AddField(
            model_name='investment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
